from pizzactrl import storyboard, fs_names

STORYBOARD = [
    storyboard.Chapter(
        # storyboard.Do(storyboard.Activity.ADVANCE_UP),
        storyboard.Do(storyboard.Activity.LIGHT_BACK,   # Bild 1
                      intensity=1.0, fade=1.0)
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('03en')),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
        storyboard.Do(storyboard.Activity.ADVANCE_UP)   # Bild 2
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.LIGHT_BACK,   # Bild 1
                      intensity=1.0, fade=1.0),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('04en')),
        storyboard.Do(storyboard.Activity.ADVANCE_UP),  # Bild 3
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('05en')),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('06en')),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('07en')),
        storyboard.Do(storyboard.Activity.ADVANCE_UP),  # Bild 4
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('08en')),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('09en')),
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=0.0),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
        storyboard.Do(storyboard.Activity.ADVANCE_UP),  # Bild 5
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=1.0),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('10en')),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('11en')),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_REC_AUDIO),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('12en')),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_REC_AUDIO),
        storyboard.Do(storyboard.Activity.RECORD_SOUND,
                      filename=fs_names.REC_NAME,
                      duration=7.0,
                      cache=True),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_STOP_REC),
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('13en')),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.REC_NAME),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('14en')),
        storyboard.Do(storyboard.Activity.ADVANCE_UP),  # Bild 6
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('15en')),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_REC_AUDIO),
        storyboard.Do(storyboard.Activity.RECORD_SOUND,
                      filename=fs_names.REC_CITY_DESC,
                      duration=60.0),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_STOP_REC),
        storyboard.Do(storyboard.Activity.ADVANCE_UP)   # Bild 7
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('16en')),
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=0.0),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_REC_AUDIO),
        storyboard.Do(storyboard.Activity.TAKE_PHOTO,
                      filename=fs_names.REC_PORTRAIT),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_SHUTTER)
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('17en')),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
        storyboard.Do(storyboard.Activity.ADVANCE_UP)
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('18en')),
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=1.0, fade=2.0),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('19en')),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('20en')),
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=0., fade=2.0),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('21en')),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
        storyboard.Do(storyboard.Activity.ADVANCE_UP)   # Bild 9
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.LIGHT_LAYER,
                      intensity=1., fade=0.5),
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=1., fade=0.5),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('22en')),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('23en')),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('24en')),
        storyboard.Do(storyboard.Activity.LIGHT_LAYER,
                      intensity=0., fade=1.),
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=0., fade=1.),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('25en')),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
        storyboard.Do(storyboard.Activity.ADVANCE_UP)   # Bild 10
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=1., fade=1.),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('26en')),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('27en')),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('28en')),
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=0., fade=1.),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('29en')),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
        storyboard.Do(storyboard.Activity.ADVANCE_UP)   # Bild 11
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=1., fade=1.),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('30en')),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('31en')),
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=0., fade=1.),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('32en')),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
        storyboard.Do(storyboard.Activity.ADVANCE_UP)   # Bild 12
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=1., fade=.5),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('33en')),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
        storyboard.Do(storyboard.Activity.ADVANCE_UP)   # Bild 13
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('34en')),
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=0., fade=1.),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_REC_AUDIO),
        storyboard.Do(storyboard.Activity.RECORD_SOUND,
                      filename=fs_names.REC_CITY_NAME,
                      duration=7.0),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_STOP_REC),
        storyboard.Do(storyboard.Activity.ADVANCE_UP)   # Bild 14
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=1., fade=1.),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('35en')),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_REC_AUDIO),
        storyboard.Do(storyboard.Activity.RECORD_SOUND,
                      filename=fs_names.REC_CITY_DESC,
                      duration=60.0),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_STOP_REC),
        storyboard.Do(storyboard.Activity.ADVANCE_UP)   # Bild 15
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('36en')),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_REC_AUDIO),
        storyboard.Do(storyboard.Activity.RECORD_SOUND,
                      filename=fs_names.REC_CITY_DESC,
                      duration=60.0),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_STOP_REC),
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=0., fade=1.),
        storyboard.Do(storyboard.Activity.ADVANCE_UP)  # Bild 16
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('37en')),
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=1., fade=1.),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('38en')),
        storyboard.Do(storyboard.Activity.ADVANCE_UP)  # Bild 17
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('39en')),
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=0., fade=1.),
        storyboard.Do(storyboard.Activity.WAIT_FOR_INPUT),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_REC_AUDIO),
        storyboard.Do(storyboard.Activity.RECORD_VIDEO,
                      filename=fs_names.REC_DRAW_CITY,
                      duration=60.0),
        storyboard.Do(storyboard.Activity.TAKE_PHOTO,
                      filename=fs_names.REC_CITY_PHOTO),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.SFX_STOP_REC),

        storyboard.Do(storyboard.Activity.ADVANCE_UP)  # Bild 18
    ),
    storyboard.Chapter(
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=1., fade=1.),
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('40en')),
        storyboard.Do(storyboard.Activity.ADVANCE_UP),  # Bild 19
        storyboard.Do(storyboard.Activity.PLAY_SOUND,
                      sound=fs_names.StoryFile('41en')),
        storyboard.Do(storyboard.Activity.LIGHT_BACK,
                      intensity=0., fade=2.)
    )
]
